optimization: 
  methodology: reinforcement_learning
  environment: MCycle_Gym_Env
  stable_baselines3_options:
    algorithm: PPO
    policy: MlpPolicy
    policy_net: [252, 252]
    qvalue_net: [252, 252]
    learning_rate: 0.0003 
    n_steps: 5
    batch_size: 16
    n_epochs: 5
    gae_lambda: 0.95
    clip_range: 0.2
    gamma: 0.99
    logdir: monitor_ppo_252_252
    tensorboard_log: False
    model_save: ppo_252_252
    action_space: discrete
    observation_space: continuous
  order: [H08,H09,H10,H11,H12,H13,H14,H15,
          I08,I09,I10,I11,I12,I13,I14,I15,
          J08,J09,J10,J11,J12,J13,J14,J15,
          K08,K09,K10,K11,K12,K13,K14,K15,
          L08,L09,L10,L11,L12,L13,L14,
          M08,M09,M10,M11,M12,M13,M14,
          N08,N09,N10,N11,N12,N13,
          O08,O09,O10,O11,
          H08,H09,H10,H11,H12,H13,H14,H15,
          I08,I09,I10,I11,I12,I13,I14,I15,
          J08,J09,J10,J11,J12,J13,J14,J15,
          K08,K09,K10,K11,K12,K13,K14,K15,
          L08,L09,L10,L11,L12,L13,L14,
          M08,M09,M10,M11,M12,M13,M14,
          N08,N09,N10,N11,N12,N13,
          O08,O09,O10,O11,
          H08,H09,H10,H11,H12,H13,H14,H15,
          I08,I09,I10,I11,I12,I13,I14,I15,
          J08,J09,J10,J11,J12,J13,J14,J15,
          K08,K09,K10,K11,K12,K13,K14,K15,
          L08,L09,L10,L11,L12,L13,L14,
          M08,M09,M10,M11,M12,M13,M14,
          N08,N09,N10,N11,N12,N13,
          O08,O09,O10,O11]
  start: state0.yml
  restart: False
  population_size: 1 
  number_of_generations: 20
  reproducer: standard
  mutation:
    method: mutate_by_genome
    initial_rate: 0.25
    final_rate: 0.55
  fixed_problem: False
  selection:
    fitness: weighted
    fitness_constraint: False
    method: tournament
  data_type: mcycle_loading_pattern_parcs332
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 1.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 400.0 
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 600.0
    cycle1_length:
      goal: greater_than_target
      target: 540
      weight: 1.0
    cycle2_length:
      goal: greater_than_target
      target: 720
      weight: 1.0
    cycle3_length:
      goal: greater_than_target
      target: 720
      weight: 1.0
    lcoe:
      goal: minimize
      weight: 20.00
genome:
  chromosomes:
    FE461: 
      type: 461
      serial: xs_g460_gd_24_wt_8
      name: FE461
      map: &ID001
        [1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1,                        
         1, 1, 1, 1]
    FE462:
      type: 462
      serial: xs_g460_gd_28_wt_8
      name: FE462
      map: *ID001
    FE501:
      type: 501
      serial: xs_g495_gd_16_wt_8
      name: FE501
      map: *ID001
    FE502:
      type: 502
      serial: xs_g495_gd_20_wt_8
      name: FE502
      map: *ID001
    FE526:
      type: 526
      serial: xs_g525_gd_32_wt_8
      name: FE526
      map: *ID001
    FE566:
      type: 566
      serial: xs_g565_gd_32_wt_8
      name: FE566
      map: *ID001
    FE586:
      type: 586
      serial: xs_g585_gd_24_wt_8
      name: FE586
      map: *ID001
    H08:
      type: H-08
      serial: no
      name: H08
      map: *ID001
    H09:
      type: H-09
      serial: no
      name: H09
      map: *ID001
    H10:
      type: H-10
      serial: no
      name: H10
      map: *ID001
    H11:
      type: H-11
      serial: no
      name: H11
      map: *ID001
    H12:
      type: H-12
      serial: no
      name: H12
      map: *ID001
    H13:
      type: H-13
      serial: no
      name: H13
      map: *ID001
    H14:
      type: H-14
      serial: no
      name: H14
      map: *ID001
    H15:
      type: H-15
      serial: no
      name: H15
      map: *ID001
    I08:
      type: I-08
      serial: no
      name: I08
      map: *ID001
    I09:
      type: I-09
      serial: no
      name: I09
      map: *ID001
    I10:
      type: I-10
      serial: no
      name: I10
      map: *ID001
    I11:
      type: I-11
      serial: no
      name: I11
      map: *ID001
    I12:
      type: I-12
      serial: no
      name: I12
      map: *ID001
    I13:
      type: I-13
      serial: no
      name: I13
      map: *ID001
    I14:
      type: I-14
      serial: no
      name: I14
      map: *ID001
    I15:
      type: I-15
      serial: no
      name: I15
      map: *ID001
    J08:
      type: J-08
      serial: no
      name: J08
      map: *ID001
    J09:
      type: J-09
      serial: no
      name: J09
      map: *ID001
    J10:
      type: J-10
      serial: no
      name: J10
      map: *ID001
    J11:
      type: J-11
      serial: no
      name: J11
      map: *ID001
    J12:
      type: J-12
      serial: no
      name: J12
      map: *ID001
    J13:
      type: J-13
      serial: no
      name: J13
      map: *ID001
    J14:
      type: J-14
      serial: no
      name: J14
      map: *ID001
    J15:
      type: J-15
      serial: no
      name: J15
      map: *ID001
    K08:
      type: K-08
      serial: no
      name: K08
      map: *ID001
    K09:
      type: K-09
      serial: no
      name: K09
      map: *ID001
    K10:
      type: K-10
      serial: no
      name: K10
      map: *ID001
    K11:
      type: K-11
      serial: no
      name: K11
      map: *ID001
    K12:
      type: K-12
      serial: no
      name: K12
      map: *ID001
    K13:
      type: K-13
      serial: no
      name: K13
      map: *ID001
    K14:
      type: K-14
      serial: no
      name: K14
      map: *ID001
    K15:
      type: K-15
      serial: no
      name: K15
      map: *ID001
    L08:
      type: L-08
      serial: no
      name: L08
      map: *ID001
    L09:
      type: L-09
      serial: no
      name: L09
      map: *ID001
    L10:
      type: L-10
      serial: no
      name: L10
      map: *ID001
    L11:
      type: L-11
      serial: no
      name: L11
      map: *ID001
    L12:
      type: L-12
      serial: no
      name: L12
      map: *ID001
    L13:
      type: L-13
      serial: no
      name: L13
      map: *ID001
    L14:
      type: L-14
      serial: no
      name: L14
      map: *ID001
    M08:
      type: M-08
      serial: no
      name: M08
      map: *ID001
    M09:
      type: M-09
      serial: no
      name: M09
      map: *ID001
    M10:
      type: M-10
      serial: no
      name: M10
      map: *ID001
    M11:
      type: M-11
      serial: no
      name: M11
      map: *ID001
    M12:
      type: M-12
      serial: no
      name: M12
      map: *ID001
    M13:
      type: M-13
      serial: no
      name: M13
      map: *ID001
    M14:
      type: M-14
      serial: no
      name: M14
      map: *ID001
    N08:
      type: N-08
      serial: no
      name: N08
      map: *ID001
    N09:
      type: N-09
      serial: no
      name: N09
      map: *ID001
    N10:
      type: N-10
      serial: no
      name: N10
      map: *ID001
    N11:
      type: N-11
      serial: no
      name: N11
      map: *ID001
    N12:
      type: N-12
      serial: no
      name: N12
      map: *ID001
    N13:
      type: N-13
      serial: no
      name: N13
      map: *ID001 
    O08:
      type: O-08
      serial: no
      name: O08
      map: *ID001
    O09:
      type: O-09
      serial: no
      name: O09
      map: *ID001
    O10:
      type: O-10
      serial: no
      name: O10
      map: *ID001
    O11:
      type: O-11
      serial: no
      name: O11
      map: *ID001 
  parcs_data:
    power: 3800.
    flow: 18231.89
    inlet_temperature: 565.0
    map_size: quarter
    symmetry: quarter
    ncycles: 3
    xs_library: /home/gkdelipe/codes/midas/MIDAS/xslib
    number_assemblies: 193
