optimization: 
  methodology: reinforcement_learning
  type:
    name: DQN
    architecture: [26, 260, 260, 260, 260, 130] 
    egreedy: 0.5
    learning_rate: 0.00001
    discount: 0.99
    return_to_state: True
    buffer_length: 32
    F_train: 8
    mini_batch_size: 8
    update_TN: 100
  population_size: 26
  number_of_generations: 100
  fixed_problem: True
  fixed_groups:
    2.0: 14
    2.5: 13
    3.2: 13
    reflector: 16
  selection:
    fitness: weighted
    method: linear
  data_type: loading_pattern
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 3.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 500.0
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 500.0
    cycle_length:
      goal: maximize
      weight: 1.00
genome:
  chromosomes:
    Assembly_One: 
      gene_group: 2.0
      type: 2
      serial: A300
      name: 2.0_w/o
      map_state: True
      map: 
        [1,
         1, 1,
         1, 1, 1,
         1, 1, 1, 1,
         1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0,
         1, 1, 1, 1, 0, 0,                          
         1, 1, 0, 0, 0,
         0, 0, 0]
    Assembly_Two:
      gene_group: 2.5
      type: 3
      serial: B300
      name: 2.5_w/o_no_bp
      map_state: True
      map: &ID001
           [1,
            1, 1,
            1, 1, 1,
            1, 1, 1, 1,
            1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 0,
            1, 1, 1, 1, 0, 0,                          
            1, 1, 0, 0, 0,
            0, 0, 0]
    Assembly_Three:
      gene_group: 3.2
      type: 5
      serial: C300
      name: 3.2_w/o_no_bp
      map_state: True
      map: *ID001
    Assembly_Four:
      gene_group: 2.5
      type: 4
      serial: D300
      name: 2.5_w/o_with_bp
      map_state: True
      map: *ID001
    Assembly_Five:
      gene_group: 3.2
      type: 6
      serial: E300
      name: 3.2_w/o_with_bp
      map_state: True
      map: *ID001
    Reflector:
      type: 1
      gene_group: reflector
      serial: none
      name: reflector
      map_state: False
      map: 
        [0,
         0, 0, 
         0, 0, 0, 
         0, 0, 0, 0, 
         0, 0, 0, 0, 0, 
         0, 0, 0, 0, 0, 1, 
         0, 0, 0, 0, 1, 1,                          
         0, 0, 1, 1, 1,
         1, 1, 1]
    symmetry_list:
        [4,
         7, 8, 
        11,12,13,
        16,17,18,19,
        22,23,24,25,26,                          
        28,29,30,31,
        33,34]
  assembly_data:
    type: pwr
    pins: 17
    core_width: 15
    load_point: 0.000
    depletion: 20
    axial_nodes: 1
    batch_number: 0
    pressure: 2250.
    boron: 900.
    power: 100.
    flow: 100.
    inlet_temperature: 550.
    map_size: quarter
    symmetry: octant
    restart_file: cycle1.res
    cs_library: cms.pwr-all.lib
    reflector: True
    number_assemblies: 157
