optimization: 
  methodology: reinforcement_learning
  environment: Cycle1_Gym_Env
  stable_baselines3_options:
    algorithm: SAC
    policy: MlpPolicy
    policy_net: [64,64]
    qvalue_net: [64,64]
    learning_rate: 0.0003
    buffer_size: 10
    learning_starts: 1
    batch_size: 16
    tau: 0.005
    gamma: 0.999
    train_freq: 1
    gradient_steps: 1
    logdir: monitor_sac_64_64
    tensorboard_log: False
    model_save: sac_mlp_64_64
    action_space: continuous
    observation_space: continuous
  order: [O08,O09,O10,O11,N13,M13,N12,M12,L12,N11,
          N10,N09,N08,M08,M09,M10,M11,L11,L10,L09,
          L08,K08,K09,K10,K11,J10,J09,J08,I08,I09,
          H08]
  start: state0.yml
  restart: False
  population_size: 1 
  number_of_generations: 20
  reproducer: standard
  mutation:
    method: mutate_by_genome
    initial_rate: 0.25
    final_rate: 0.55
  fixed_problem: False
  selection:
    fitness: weighted
    fitness_constraint: False
    method: tournament
  data_type: loading_patternsimple_parcs332
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 1.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 400.0 
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 600.0      
    cycle_length:
      goal: maximize
      weight: 1.00
genome:
  chromosomes:
    FE200: 
      type: 200
      serial: xs_g200_gd_0_bp_0
      name: FE200
      map: &ID001
        [1,
         1, 1,
         1, 1, 1,
         1, 1, 1, 1,
         1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1,                        
         1, 1, 1, 1]
    FE250:
      type: 250
      serial: xs_g250_gd_0_bp_0
      name: FE250
      map: *ID001
    FE251:
      type: 251
      serial: xs_g250_gd_16_bp_0
      name: FE251
      map: *ID001
    FE320:
      type: 320
      serial: xs_g320_gd_0_bp_0
      name: FE280
      map: *ID001
    FE321:
      type: 321
      serial: xs_g320_gd_16_bp_0
      name: FE321
      map: *ID001
  parcs_data:
    power: 3800.
    flow: 18231.89
    inlet_temperature: 565.0
    map_size: quarter
    symmetry: octant
    xs_library: /home/gkdelipe/codes/mof/MOF/xslib
    number_assemblies: 193
